version: "3.9"
services:
    mongodb:
        container_name: mongodb
        image: mongo:5.0
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: $DB_USER
            MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
        volumes:
            - ./data:/data/db
            - ./data/logs:/var/logs/mongodb/
        ports:
            - "5062:27017"
        networks:
            - backend
    redis:
        container_name: redis
        image: redis:6.2.6
        ports:
            - "5063:6379"
        networks:
            - backend
        volumes:
            - .redis.conf:/usr/local/etc/redis/redis.conf
    api:
        container_name: api
        build: .
        ports:
            - "5061:4100"
        networks:
            - backend
        env_file:
            - .env
networks:
    backend:
        driver: bridge
